### PR TITLE
Fix build failure

### PR DESCRIPTION
**Pull request by jbeorse**

### CODE REVIEW

**Comment by linl33** [comment]
Why did you lock it to 214a instead of using any subversion of 214?

**Comment by jbeorse** [comment]
I'm not sure how to include any subversions. I'm not particularly familiar with maven's syntax. 

The way it was before it would not build as it couldn't find the correct sync-client version. This change will allow it to build, but need to be updated for each new sub version of sync-client which is not ideal. I submitted this quickly since the build was broken.

I assumed that either the tip had a typo or that our versioning wasn't done correctly, since maven didn't seem to recognize 214a as a sub version of 214. If you have the right fix I'm happy to merge that instead of what I did.

**Comment by linl33** [comment]
pom.xml wasn't updated to use 214, this would fix it `[2.0 rev 214, 2.0 rev 215)`.

**Comment by jbeorse** [comment]
Ah ok, I see how it works now. I've updated this pull request with your suggestion

**Pull request merged**
